# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: GitHub Actions for Scientific Data Workflows (SciPy 2024)
author: Valentina Staneva, George (Quinn) Brencher, Scott Henderson
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/uwescience/SciPy2024-GitHubActionsTutorial  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: lesson_content  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
